services:
  db:
    image: postgres:16
    container_name: cloudapp-db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: cloudapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/CloudAppBackend
      dockerfile: Dockerfile
    container_name: cloudapp-backend
    ports:
      - "8081:8081"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cloudapp-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data: